version: 0.2

env:
  variables:
    PROJECT_NAME: "aws-devops"
    IMAGE_TAG: "latest"
    PRIMARY_REGION: "us-east-1"
    SECONDARY_REGION: "us-east-2"
    # ENV is injected by CodeBuild project (prod or staging)

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo Installing dependencies...
      - echo "Using Java version:"
      - java -version
      - mvn -version

  pre_build:
    commands:
      - echo Logging in to Amazon ECR in primary region...
      - PRIMARY_REPO_URL=$(aws ecr describe-repositories --region $PRIMARY_REGION --repository-names ${PROJECT_NAME}-${ENV} --query 'repositories[0].repositoryUri' --output text)
      - aws ecr get-login-password --region $PRIMARY_REGION | docker login --username AWS --password-stdin $PRIMARY_REPO_URL

      - echo Logging in to Amazon ECR in secondary region...
      - SECONDARY_REPO_URL=$(aws ecr describe-repositories --region $SECONDARY_REGION --repository-names ${PROJECT_NAME}-${ENV} --query 'repositories[0].repositoryUri' --output text)
      - aws ecr get-login-password --region $SECONDARY_REGION | docker login --username AWS --password-stdin $SECONDARY_REPO_URL

  build:
    commands:
      - echo Running Maven build with Java 21...
      - mvn clean package
      
      - echo Building Docker image...
      - docker build -t app:$IMAGE_TAG app/

  post_build:
    commands:
      - echo Tagging and pushing Docker image to primary ECR...
      - docker tag app:$IMAGE_TAG $PRIMARY_REPO_URL:$IMAGE_TAG
      - docker push $PRIMARY_REPO_URL:$IMAGE_TAG

      - echo Tagging and pushing Docker image to secondary ECR...
      - docker tag app:$IMAGE_TAG $SECONDARY_REPO_URL:$IMAGE_TAG
      - docker push $SECONDARY_REPO_URL:$IMAGE_TAG

      - echo Forcing new ECS deployments for $ENV environment...
      - |
        if [ "$ENV" = "staging" ]; then
          # Staging cluster/service names (single region)
          aws ecs update-service \
            --region $PRIMARY_REGION \
            --cluster ${PROJECT_NAME}-${ENV}-cluster \
            --service ${PROJECT_NAME}-${ENV}-svc \
            --force-new-deployment
        else
          # Prod cluster/service names (multi-region)
          aws ecs update-service \
            --region $PRIMARY_REGION \
            --cluster ${PROJECT_NAME}-${ENV}-cluster-primary \
            --service ${PROJECT_NAME}-${ENV}-svc-primary \
            --force-new-deployment

          aws ecs update-service \
            --region $SECONDARY_REGION \
            --cluster ${PROJECT_NAME}-${ENV}-cluster-secondary \
            --service ${PROJECT_NAME}-${ENV}-svc-secondary \
            --force-new-deployment
        fi

artifacts:
  files:
    - '**/*'